from sqlalchemy import Column, String, Date, Integer, ForeignKey
from sqlalchemy.dialects.mysql import DOUBLE
from sqlalchemy.orm import relationship
from .database import Base
from datetime import date

# =====================================================================
# 1. SUPERVISOR ORM MODEL
# =====================================================================
# Represents the administrators/supervisors who manage the web dashboard.
# Handles web portal authentication and profile metadata.
class Supervisor(Base):
    __tablename__ = "supervisors"
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    email = Column(String(100), unique=True, index=True, nullable=False)
    password_hash = Column(String(255), nullable=False)
    profile_pic_url = Column(String(255), nullable=True)

# =====================================================================
# 2. WORKER ORM MODEL
# =====================================================================
# Represents the field workers responsible for cleaning assigned sites.
# Includes credentials for the mobile application and tracks availability.
class Worker(Base):
    __tablename__ = "workers"
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    phone = Column(String(20), unique=True, nullable=False)
    password_hash = Column(String(255), nullable=False) # Used for mobile app authentication
    status = Column(String(50), default="Available") 
    
    # Defines a one-to-many relationship: One worker can have multiple assigned tasks.
    tasks = relationship("TrashDetection", back_populates="assigned_worker")

# =====================================================================
# 3. TRASH DETECTION ORM MODEL
# =====================================================================
# Core entity representing an AI-detected trash anomaly.
# Stores geospatial coordinates, image evidence, and task lifecycle status.
class TrashDetection(Base):
    __tablename__ = "trash_detections"

    # Unique identifier generated by the AI processing pipeline (e.g., "waste_site_4_2026-02-16").
    id = Column(String(255), primary_key=True, index=True)
    site_name = Column(String(255))
    filename = Column(String(255)) 
    latitude = Column(DOUBLE)  
    longitude = Column(DOUBLE)
    status = Column(String(50), default="Pending")
    image_url = Column(String(500))
    detection_date = Column(Date, default=date.today)

    # -----------------------------------------------------------------
    # TASK ASSIGNMENT & PROOF TRACKING
    # -----------------------------------------------------------------
    # proof_url: Stores the path to the worker's post-cleanup evidence photo.
    proof_url = Column(String(500), nullable=True) 
    # worker_id: Establishes a Foreign Key constraint linking to the workers table.
    worker_id = Column(Integer, ForeignKey("workers.id"), nullable=True) 
    
    # Maps the relationship back to the Worker ORM model.
    assigned_worker = relationship("Worker", back_populates="tasks")